name: Windows
on:
  pull_request:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
  test:
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: stable, os: windows-latest }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ matrix.rust }}
          command: test
          args: --features with-db